version: '3.8'

services:

    db:
        image: mongo
        restart: always
        container_name: mongodb
        ports:
            - "27017:27017"
        # command: [--auth]
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - mongo_data:/data/db

volumes:
  mongo_data: